export function HomePage({ navigate }) { return <><div className="welcome"><div><span className="eyebrow accent">CENTRE DE DIAGNOSTIC</span><h2>Bonjour, technicien.</h2><p>Lancez un diagnostic ponctuel et suivez les derniers essais moteurs.</p></div><div className="welcome-icon">⚙</div></div><section className="page-grid two"><ActionCard icon="✎" title="Test manuel" text="Saisir les mesures relevées par le technicien." action={() => navigate('motor')} label="Commencer" /><ActionCard icon="⌁" title="Test automatique" text="Connecter le kit ESP32 et acquérir les mesures." action={() => navigate('kit')} label="Connecter le kit" /></section><SectionTitle title="Derniers tests" action="Voir l'historique" onAction={() => navigate('history')} /><div className="empty-state"><span>▤</span><strong>Aucun diagnostic enregistré</strong><p>Les diagnostics terminés apparaîtront ici.</p></div></> }
function ActionCard({ icon, title, text, action, label }) { return <article className="action-card"><span className="action-icon">{icon}</span><div><h3>{title}</h3><p>{text}</p><button className="button primary" onClick={action}>{label} <span>→</span></button></div></article> }
export function KitConnectionPage({ navigate }) { return <><SectionIntro eyebrow="ÉTAPE 1 / 8" title="Connecter le kit de diagnostic" text="Vérifiez la liaison avec le kit avant de commencer l'acquisition." /><div className="connection-card"><div className="connection-visual"><div className="kit-orb">⌁</div><span className="status-pill neutral">Non connecté</span></div><div className="connection-details"><h3>Kit de diagnostic</h3><dl><dt>Identifiant</dt><dd>—</dd><dt>ESP32</dt><dd>En attente de détection</dd><dt>Firmware</dt><dd>—</dd></dl><button className="button primary" onClick={() => navigate('motor')}>Connecter le kit <span>→</span></button><p className="muted">La connexion réelle MQTT sera activée à l'étape 7.</p></div></div></> }
export function MotorFormPage({ navigate }) { return <><SectionIntro eyebrow="ÉTAPE 2 / 8" title="Identifier le moteur" text="Une seule fiche de diagnostic est utilisée pour les modes manuel et automatique." /><div className="form-card"><div className="form-section"><h3>Identification</h3><div className="form-grid">{['ID moteur', 'Matricule', 'Désignation', 'Marque', 'Modèle', 'Service'].map((x) => <label key={x}>{x}<input placeholder={`Saisir ${x.toLowerCase()}`} /></label>)}</div></div><div className="form-section"><h3>Données de référence</h3><div className="form-grid">{['Puissance nominale (kW)', 'Tension nominale (V)', 'Courant nominal (A)', 'Vitesse (tr/min)'].map((x) => <label key={x}>{x}<input placeholder="—" /></label>)}</div></div><div className="form-actions"><button className="button secondary" onClick={() => navigate('home')}>Annuler</button><button className="button primary" onClick={() => navigate('acquisition')}>Continuer <span>→</span></button></div></div></> }
export function AcquisitionPage({ navigate }) { return <><SectionIntro eyebrow="ÉTAPE 3 / 8" title="Acquisition des mesures" text="Le test automatique acquiert température, courant et vibration pendant environ 60 secondes." /><div className="acquisition-card"><div className="acquisition-status"><span className="big-status-dot" /><span>En attente</span><small>Le kit doit être connecté pour démarrer.</small></div><div className="progress-track"><span /></div><div className="acquisition-actions"><button className="button primary" disabled>START</button><button className="button secondary" onClick={() => navigate('home')}>Quitter</button></div><div className="state-list"><span className="done">IDLE</span><span>READY</span><span>ACQUIRING</span><span>COMPLETED</span></div></div></> }
export function GraphPage() { return <Placeholder title="Visualisation des mesures" eyebrow="ÉTAPE 4 / 8" text="Les trois graphiques température, courant et vibration seront ajoutés à l'étape 9." /> }
export function AnalysisPage() { return <Placeholder title="Analyse du diagnostic" eyebrow="ÉTAPE 5 / 8" text="L'analyse paramètre par paramètre et les règles modulaires seront ajoutées à l'étape 10." /> }
export function ReportPage() { return <Placeholder title="Rapport de diagnostic" eyebrow="ÉTAPE 6 / 8" text="Le rapport PDF officiel sera généré côté backend à l'étape 12." /> }
export function HistoryPage() { return <><SectionIntro eyebrow="HISTORIQUE" title="Diagnostics enregistrés" text="Chaque test sera conservé indépendamment pour assurer la traçabilité." /><div className="table-card"><div className="table-toolbar"><input placeholder="Rechercher un moteur ou matricule…" /><button className="button secondary">Filtrer</button></div><div className="empty-state compact"><span>▤</span><strong>Historique vide</strong><p>Les tests terminés apparaîtront dans ce tableau.</p></div></div></> }
function Placeholder({ title, eyebrow, text }) { return <><SectionIntro eyebrow={eyebrow} title={title} text={text} /><div className="coming-soon"><span>◌</span><h3>Module prévu dans une prochaine étape</h3><p>Cette page est déjà reliée à la navigation afin de préparer le parcours complet.</p></div></> }
function SectionIntro({ eyebrow, title, text }) { return <div className="section-intro"><span className="eyebrow accent">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div> }
function SectionTitle({ title, action, onAction }) { return <div className="section-title"><h2>{title}</h2><button onClick={onAction}>{action} →</button></div> }
